language: minimal
dist: jammy

before_install:
  - sudo apt-get update
  - sudo apt-get install -y build-essential libssl-dev libreadline-dev zlib1g-dev libffi-dev libyaml-dev

install:
  - |
    if wget -q --spider https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.6.tar.gz; then
      RUBY_VERSION=3.3.6
    else
      RUBY_VERSION=3.3.5
    fi
    echo "Using Ruby version: $RUBY_VERSION"
    wget https://cache.ruby-lang.org/pub/ruby/3.3/ruby-${RUBY_VERSION}.tar.gz
    tar -xzf ruby-${RUBY_VERSION}.tar.gz
    cd ruby-${RUBY_VERSION}
    ./configure --prefix=$HOME/ruby --disable-install-doc
    make -j$(nproc)
    make install
    export PATH=$HOME/ruby/bin:$PATH
    cd ..

script:
  - export PATH=$HOME/ruby/bin:$PATH
  - ruby --version
  - ruby -e "puts 'Ruby installation successful!'"

cache:
  directories:
    - $HOME/ruby
